### PR TITLE
Fix older kernel handling for Fentry

### LINKED ISSUE #369: can't instantiate NetObserv eBPF Agent on kernel 5.4
I'm trying to run it on kernel 5.4 (Ubuntu 20, 5.4.0-189-generic) and it fails with
`FATA[0000] can't instantiate NetObserv eBPF Agent        error="loading and assigning BPF objects: field EgressFlowParse: program egress_flow_parse: map direct_flows: map create without BTF: invalid argument"`

Is there any way to make it work because upgrading all the servers is not realistic atm.

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

Fix upstream #369 

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Will this change affect NetObserv / Network Observability operator? If not, you can ignore the rest of this checklist.
* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

File: pkg/ebpf/tracer.go [hunk 1]
```diff
@@ -168,16 +170,20 @@ func NewFlowFetcher(cfg *FlowFetcherConfig) (*FlowFetcher, error) {
...
-			rttKprobeLink, err = link.Kprobe("tcp_rcv_established", objects.TcpRcvKprobe, nil)
-			if err != nil {
-				return nil, fmt.Errorf("failed to attach the BPF program to tcpReceiveKprobe: %w", err)
-			}
+			// Fall through to use kprobe
+		}
+		// try to use kprobe for older kernels
+		rttKprobeLink, err = link.Kprobe("tcp_rcv_established", objects.TcpRcvKprobe, nil)
+		if err != nil {
+			log.Warningf("failed to attach the BPF program to tcpReceiveFentry: %v fallback to use kprobe", err)
```
Comment (matijavizintin) [inline pkg/ebpf/tracer.go:185]: This warn is not always correct. In case of new kernel tcp_rcv_fentry can be successfully attached and the code will continue and fail with kprobe.

Comment (msherif1234) [reply pkg/ebpf/tracer.go:185]: yeah good catch I will fix it Thanks!!

**Review by matijavizintin — APPROVED** [review]

File: pkg/ebpf/tracer.go [hunk 2]
```diff
@@ -85,6 +86,7 @@ type FlowFetcherConfig struct {
 	FilterConfig     *FilterConfig
 }
 
+// nolint:cyclop
```
Comment (jpinsonneau) [inline pkg/ebpf/tracer.go:89]: Can't we split the function here ?

**Review by jpinsonneau — APPROVED** [review]
Looks good to me, just a comment

File: pkg/ebpf/tracer.go (hunk 2 above)
Comment (msherif1234) [reply pkg/ebpf/tracer.go:89]: we probably can will do that in a follow on pr
