### PR TITLE
NETOBSERV-2031: fix agent verifier issue and userspace crash with no features

### LINKED ISSUE #498: netobserv-ebpf-agent failed to start
I follow the [instructions ](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/examples/flowlogs-dump/README.md), but I got the error: 
```
        379: (6b) *(u16 *)(r10 -274) = r1
        380: (69) r1 = *(u16 *)(r2 +2)
        381: (6b) *(u16 *)(r10 -272) = r1
        382: (bf) r2 = r10
        ;
        383: (07) r2 += -128
        384: (bf) r3 = r10
        385: (07) r3 += -280
        ; long ret = bpf_map_update_elem(&aggregated_flows, &id, &new_flow, BPF_NOEXIST);
        386: (18) r1 = 0xffff95bf43885800
        388: (b7) r4 = 1
        389: (85) call bpf_map_update_elem#2
        invalid indirect read from stack R3 off -280+18 size 56
        processed 226 insns (limit 1000000) max_states_per_insn 0 total_states 10 peak_states 10 mark_read 8  component=ebpf.FlowFetcher
FATA[0000] can't instantiate NetObserv eBPF Agent        error="loading and assigning BPF objects: field TcEgressFlowParse: program tc_egress_flow_parse: load program: permission denied: invalid indirect read from stack R3 off -280+18 size 56 (322 line(s) omitted)"
```

when I execute the command:
```
sudo TARGET_HOST=127.0.0.1 TARGET_PORT=9999 ./bin/netobserv-ebpf-agent
```

the `./bin/flowlogs-dump-collector` normally startup

My env:
```
uname -r:
5.10.134-16.2.al8.x86_64
```

I am a newbee of eBPF,  would you please give me some help.

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

with OCP 4.15 and older basically rhel9.2 ebpf verifier didn't tolerate uninitialized flow metrics, also there was a crash in tracer code when no features referencing null pointer
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x212d705]

goroutine 45 [running]:
github.com/cilium/ebpf.newMapIterator(...)
	/opt/app-root/vendor/github.com/cilium/ebpf/map.go:1558
github.com/cilium/ebpf.(*Map).Iterate(...)
	/opt/app-root/vendor/github.com/cilium/ebpf/map.go:1290
github.com/netobserv/netobserv-ebpf-agent/pkg/tracer.(*FlowFetcher).LookupAndDeleteMap(0xc0042c0840, 0xc00017a960)
	/opt/app-root/pkg/tracer/tracer.go:888 +0x785
github.com/netobserv/netobserv-ebpf-agent/pkg/flow.(*MapTracer).evictFlows(0xc00428dac0, {0x2c88880, 0xc00424afa0}, 0x1, 0xc000c09570)
	/opt/app-root/pkg/flow/tracer_map.go:102 +0x8f
github.com/netobserv/netobserv-ebpf-agent/pkg/flow.(*MapTracer).evictionSynchronization(0xc00428dac0, {0x2c88880, 0xc00424afa0}, 0x1, 0xc000c09570)
	/opt/app-root/pkg/flow/tracer_map.go:89 +0x85
created by github.com/netobserv/netobserv-ebpf-agent/pkg/agent.(*Flows).buildAndStartPipeline.(*MapTracer).TraceLoop.func1 in goroutine 92
	/opt/app-root/pkg/flow/tracer_map.go:58 +0xd1
```
both issues are side effect of https://github.com/netobserv/netobserv-ebpf-agent/pull/469
also fixes #498 
## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Will this change affect NetObserv / Network Observability operator? If not, you can ignore the rest of this checklist.
* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

File: bpf/flows.c [hunk 1]
```diff
@@ -140,16 +140,15 @@ static inline int flow_monitor(struct __sk_buff *skb, u8 direction) {
         update_existing_flow(aggregate_flow, &pkt, len, filter_sampling);
     } else {
         // Key does not exist in the map, and will need to create a new entry.
-        flow_metrics new_flow = {
```
Comment (jotak) [inline bpf/flows.c:143]: we use designated init in many places, should we change all of them?

Comment (msherif1234) [reply bpf/flows.c:143]: not for flow_metrics , I think the old version of verifier wasn't happy with the embedded spin lock struct w/o initializtion

File: pkg/tracer/tracer.go [hunk 2]
```diff
@@ -885,35 +885,37 @@ func (m *FlowFetcher) LookupAndDeleteMap(met *metrics.Metrics) map[ebpf.BpfFlowI
...
-
-	countAdditional := 0
-	for i, id := range ids {
-		countAdditional++
-		if err := m.objects.AdditionalFlowMetrics.LookupAndDelete(&id, &additionalMetrics); err != nil {
-			if i == 0 && errors.Is(err, cilium.ErrNotSupported) {
-				log.WithError(err).Warnf("switching to legacy mode")
-				m.lookupAndDeleteSupported = false
-				return m.legacyLookupAndDeleteMap(met)
+	if m.objects.AdditionalFlowMetrics != nil {
```
Comment (jotak) [inline pkg/tracer/tracer.go:888]: actually, looking at the code, I'm not sure this is what we want here. I rather think that the root cause is missing stuff in paths where bpf objects are being reassigned. In `kernelSpecificLoadAndAssign`.
Also I realize the map object isn't closed in `Close` func

Comment (msherif1234) [reply pkg/tracer/tracer.go:888]: hmm look at the stack trace in the PR description we are referrencing null ptr ?

Comment (msherif1234) [reply pkg/tracer/tracer.go:891]: I did add handle to kernelspecific and added the missing close while I am here

Comment (msherif1234) [reply pkg/tracer/tracer.go:891]: should I keep the sanity check in lookupAndDelete for null ptr ? or not needed anymore ?

Comment (msherif1234) [reply pkg/tracer/tracer.go]: I removed it will retest

Comment (jotak) [reply pkg/tracer/tracer.go]: thanks ... and sorry for missing all that previously

**Review by jotak — APPROVED** [review]
/lgtm
